name: fl3-kaggle
channels:
  - huggingface
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12.4
  - protobuf
  - jupyterlab
  - pandas
  - datasets
  - ipywidgets
  - pytorch
  - torchvision
  - sentencepiece
  - transformers
  - matplotlib
  - scikit-learn
  - scipy
  - accelerate
